server:
  port: 8080

spring:
  application: api-gateway
  
  cloud:
    gateway:
      routes:
      # Route requests starting with /api/orders to order-service
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          filters:
            - JwtAuthenticationFilter
            - RewritePath=/api/(?<segment>.*), /${segment} # Add a space or quotes if it fails


        # Route requests starting with /api/inventory to inventory-service
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory/**
          filters:
            - JwtAuthenticationFilter

        # Route requests starting with /api/auth to identity-service
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/api/auth/**

# Eureka server configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Tells the gateway where the Eureka server is.
